### ISSUE TITLE
Fix Carthage example project configuration

### ISSUE THREAD

**Issue by mtnbarreto** [chamitha/LocationRow#4]
`$(BUILT_PRODUCTS_DIR)/$(FRAMEWORKS_FOLDER_PATH)/Eureka.framework` missing from Output files. 

<img width="827" alt="screen shot 2019-02-25 at 5 26 02 pm" src="https://user-images.githubusercontent.com/1746532/53366500-7ec4aa80-3922-11e9-8ea1-10c4c8c67356.png">

**Comment by chamitha** [comment]
Fixed in bb08ef921c681af0cad23bb32f2bc9047b59f43f

**Comment by chamitha** [comment]
Fixed in bb08ef921c681af0cad23bb32f2bc9047b59f43f
